version: '3'
services:
  xiaomi-ble-mqtt:
    container_name: xiaomi-ble-mqtt
    image: xiaomi-ble-mqtt
    build:
      context: .
      dockerfile: contrib/Dockerfile
    privileged: true
    volumes:
      - "./:/usr/src/app/"
    network_mode: host
  # mosquitto:
  #   container_name: mosquitto
  #   image: eclipse-mosquitto:1.6.9
  #   # ports:
  #   #   - 1883:1883
  #   #   - 9001:9001
  #   network_mode: host