version: '3'
services:
  xiaomi-ble-mqtt:
    container_name: xiaomi-ble-mqtt
    image: xiaomi-ble-mqtt
    build:
      context: .
      dockerfile: contrib/Dockerfile
    privileged: true
    volumes:
      - "./:/usr/src/app/"
    networks: 
      - mqtt
  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto:1.6.9
    networks: 
      - mqtt
networks: 
  mqtt: